# D = Steep::Diagnostic
#
target :lib do
  signature "sig"
  check "lib"
  check "runner"
  library "date"
end

# target :test do
#   signature "sig", "sig-private"
#
#   check "test"
#
#   # library "pathname", "set"       # Standard libraries
# end
